[package]
name = "xd"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3"
chrono = "0.4"
ratatui = "0.29"
crossterm = "0.29"
dirs = "5.0"
ratatui-code-editor = "0.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2"
regex = "1"
zip = "2.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
nix = { version = "0.29", features = ["term", "poll", "fs", "process", "signal"] }
